

const createDraftCombineQuery = `
CREATE TABLE draft_combine (
            yearCombine VARCHAR,
            idPlayer VARCHAR,
            nameFirst VARCHAR,
            nameLast VARCHAR,
            namePlayer VARCHAR,
            slugPosition VARCHAR,
            heightWOShoesInches VARCHAR,
            heightWOShoes VARCHAR,
            weightLBS VARCHAR,
            wingspanInches VARCHAR,
            wingspan VARCHAR,
            reachStandingInches VARCHAR,
            reachStandingO VARCHAR,
            verticalLeapStandingInches VARCHAR,
            verticalLeapMaxInches VARCHAR,
            timeLaneAgility VARCHAR,
            timeThreeQuarterCourtSprint VARCHAR,
            repsBenchPress135 VARCHAR,
            pctBodyFat VARCHAR,
            heightWShoesInches VARCHAR,
            heightWShoes VARCHAR,
            lengthHandInches VARCHAR,
            widthHandInches VARCHAR,
            timeModifiedLaneAgility VARCHAR,
            setSpot15CornerLeft VARCHAR,
            setSpot15BreakLeft VARCHAR,
            setSpot15TopKey VARCHAR,
            setSpot15BreakRight VARCHAR,
            setSpot15CornerRight VARCHAR,
            setSpot15CornerLeftCollege VARCHAR,
            setSpot15BreakLeftCollege VARCHAR,
            setSpot15TopKeyCollege VARCHAR,
            setSpot15BreakRightCollege VARCHAR,
            setSpot15CornerRightCollege VARCHAR,
            setSpot15CornerLeftNBA VARCHAR,
            setSpot15BreakLeftNBA VARCHAR,
            setSpot15TopKeyNBA VARCHAR,
            setSpotBreakRightNBA VARCHAR,
            setSpotCornerRightNBA VARCHAR,
            setSpot15CornerLeftMade VARCHAR,
            setSpot15CornerLeftAttempted VARCHAR,
            setSpot15CornerLeftPct VARCHAR,
            setSpot15BreakLeftMade VARCHAR,
            setSpot15BreakLeftAttempted VARCHAR,
            setSpot15BreakLeftPct VARCHAR,
            setSpot15TopKeyMade VARCHAR,
            setSpot15TopKeyAttempted VARCHAR,
            setSpot15TopKeyPct VARCHAR,
            setSpot15BreakRightMade VARCHAR,
            setSpot15BreakRightAttempted VARCHAR,
            setSpot15BreakRightPct VARCHAR,
            setSpot15CornerRightMade VARCHAR,
            setSpot15CornerRightAttempted VARCHAR,
            setSpot15CornerRightPct VARCHAR,
            setSpot15CornerLeftCollegeMade VARCHAR,
            setSpot15CornerLeftCollegeAttempted VARCHAR,
            setSpot15CornerLeftCollegePct VARCHAR,
            setSpot15BreakLeftCollegeMade VARCHAR,
            setSpot15BreakLeftCollegeAttempted VARCHAR,
            setSpot15BreakLeftCollegePct VARCHAR,
            setSpot15TopKeyCollegeMade VARCHAR,
            setSpot15TopKeyCollegeAttempted VARCHAR,
            setSpot15TopKeyCollegePct VARCHAR,
            setSpot15BreakRightCollegeMade VARCHAR,
            setSpot15BreakRightCollegeAttempted VARCHAR,
            setSpot15BreakRightCollegePct VARCHAR,
            setSpot15CornerRightCollegeMade VARCHAR,
            setSpot15CornerRightCollegeAttempted VARCHAR,
            setSpot15CornerRightCollegePct VARCHAR,
            setSpot15CornerLeftNBAMade VARCHAR,
            setSpot15CornerLeftNBAAttempted VARCHAR,
            setSpot15CornerLeftNBAPct VARCHAR,
            setSpot15BreakLeftNBAMade VARCHAR,
            setSpot15BreakLeftNBAAttempted VARCHAR,
            setSpot15BreakLeftNBAPct VARCHAR,
            setSpot15TopKeyNBAMade VARCHAR,
            setSpot15TopKeyNBAAttempted VARCHAR,
            setSpot15TopKeyNBAPct VARCHAR,
            setSpotBreakRightNBAMade VARCHAR,
            setSpotBreakRightNBAAttempted VARCHAR,
            setSpotBreakRightNBAPct VARCHAR,
            setSpotCornerRightNBAMade VARCHAR,
            setSpotCornerRightNBAAttempted VARCHAR,
            setSpotCornerRightNBAPct VARCHAR,
            setOffDrib15BreakLeft VARCHAR,
            setSpotOffDrib15TopKey VARCHAR,
            setOffDrib15BreakRight VARCHAR,
            setOnMove15 VARCHAR,
            setOnMoveCollege VARCHAR,
            setOffDrib15BreakLeftMade VARCHAR,
            setOffDrib15BreakLeftAttempted VARCHAR,
            setOffDrib15BreakLeftPct VARCHAR,
            setSpotOffDrib15TopKeyMade VARCHAR,
            setSpotOffDrib15TopKeyAttempted VARCHAR,
            setSpotOffDrib15TopKeyPct VARCHAR,
            setOffDrib15BreakRightMade VARCHAR,
            setOffDrib15BreakRightAttempted VARCHAR,
            setOffDrib15BreakRightPct VARCHAR,
            setOnMove15Made VARCHAR,
            setOnMove15Attempted VARCHAR,
            setOnMove15Pct VARCHAR,
            setOnMoveCollegeMade VARCHAR,
            setOnMoveCollegeAttempted VARCHAR,
            setOnMoveCollegePct VARCHAR,
            setOffDribBreakLeftCollege VARCHAR,
            setOffDribTopKeyCollege VARCHAR,
            setOffDribBreakRightCollege VARCHAR,
            setOffDribBreakLeftCollegeMade VARCHAR,
            setOffDribBreakLeftCollegeAttempted VARCHAR,
            setOffDribBreakLeftCollegePct VARCHAR,
            setOffDribTopKeyCollegeMade VARCHAR,
            setOffDribTopKeyCollegeAttempted VARCHAR,
            setOffDribTopKeyCollegePct VARCHAR,
            setOffDribBreakRightCollegeMade VARCHAR,
            setOffDribBreakRightCollegeAttempted VARCHAR,
            setOffDribBreakRightCollegePct VARCHAR
        )
`

const createDraftQuery = `
CREATE TABLE draft(
    yearDraft VARCHAR,
    numberPickOverall VARCHAR,
    numberRound VARCHAR,
    numberRoundPick VARCHAR,
    namePlayer VARCHAR,
    slugTeam VARCHAR,
    nameOrganizationFrom VARCHAR,
    typeOrganizationFrom VARCHAR,
    idPlayer VARCHAR,
    idTeam VARCHAR,
    nameTeam VARCHAR,
    cityTeam VARCHAR,
    teamName VARCHAR,
    PLAYER_PROFILE_FLAG VARCHAR,
    slugOrganizationTypeFrom VARCHAR,
    locationOrganizationFrom VARCHAR
)
`


module.exports = { createDraftCombineQuery, createDraftQuery };