

const createDraftCombineQuery = `
CREATE TABLE draft_combine (
            yearCombine INTEGER,
            idPlayer INTEGER,
            nameFirst VARCHAR,
            nameLast VARCHAR,
            namePlayer VARCHAR,
            slugPosition VARCHAR,
            heightWOShoesInches VARCHAR,
            heightWOShoes VARCHAR,
            weightLBS VARCHAR,
            wingspanInches VARCHAR,
            wingspan VARCHAR,
            reachStandingInches VARCHAR,
            reachStandingO VARCHAR,
            verticalLeapStandingInches VARCHAR,
            verticalLeapMaxInches VARCHAR,
            timeLaneAgility VARCHAR,
            timeThreeQuarterCourtSprint VARCHAR,
            repsBenchPress135 VARCHAR,
            pctBodyFat VARCHAR,
            heightWShoesInches VARCHAR,
            heightWShoes VARCHAR,
            lengthHandInches VARCHAR,
            widthHandInches VARCHAR,
            timeModifiedLaneAgility VARCHAR,
            setSpot15CornerLeft VARCHAR,
            setSpot15BreakLeft VARCHAR,
            setSpot15TopKey VARCHAR,
            setSpot15BreakRight VARCHAR,
            setSpot15CornerRight VARCHAR,
            setSpot15CornerLeftCollege VARCHAR,
            setSpot15BreakLeftCollege VARCHAR,
            setSpot15TopKeyCollege VARCHAR,
            setSpot15BreakRightCollege VARCHAR,
            setSpot15CornerRightCollege VARCHAR,
            setSpot15CornerLeftNBA VARCHAR,
            setSpot15BreakLeftNBA VARCHAR,
            setSpot15TopKeyNBA VARCHAR,
            setSpotBreakRightNBA VARCHAR,
            setSpotCornerRightNBA VARCHAR,
            setSpot15CornerLeftMade VARCHAR,
            setSpot15CornerLeftAttempted VARCHAR,
            setSpot15CornerLeftPct VARCHAR,
            setSpot15BreakLeftMade VARCHAR,
            setSpot15BreakLeftAttempted VARCHAR,
            setSpot15BreakLeftPct VARCHAR,
            setSpot15TopKeyMade VARCHAR,
            setSpot15TopKeyAttempted VARCHAR,
            setSpot15TopKeyPct VARCHAR,
            setSpot15BreakRightMade VARCHAR,
            setSpot15BreakRightAttempted VARCHAR,
            setSpot15BreakRightPct VARCHAR,
            setSpot15CornerRightMade VARCHAR,
            setSpot15CornerRightAttempted VARCHAR,
            setSpot15CornerRightPct VARCHAR,
            setSpot15CornerLeftCollegeMade VARCHAR,
            setSpot15CornerLeftCollegeAttempted VARCHAR,
            setSpot15CornerLeftCollegePct VARCHAR,
            setSpot15BreakLeftCollegeMade VARCHAR,
            setSpot15BreakLeftCollegeAttempted VARCHAR,
            setSpot15BreakLeftCollegePct VARCHAR,
            setSpot15TopKeyCollegeMade VARCHAR,
            setSpot15TopKeyCollegeAttempted VARCHAR,
            setSpot15TopKeyCollegePct VARCHAR,
            setSpot15BreakRightCollegeMade VARCHAR,
            setSpot15BreakRightCollegeAttempted VARCHAR,
            setSpot15BreakRightCollegePct VARCHAR,
            setSpot15CornerRightCollegeMade VARCHAR,
            setSpot15CornerRightCollegeAttempted VARCHAR,
            setSpot15CornerRightCollegePct VARCHAR,
            setSpot15CornerLeftNBAMade VARCHAR,
            setSpot15CornerLeftNBAAttempted VARCHAR,
            setSpot15CornerLeftNBAPct VARCHAR,
            setSpot15BreakLeftNBAMade VARCHAR,
            setSpot15BreakLeftNBAAttempted VARCHAR,
            setSpot15BreakLeftNBAPct VARCHAR,
            setSpot15TopKeyNBAMade VARCHAR,
            setSpot15TopKeyNBAAttempted VARCHAR,
            setSpot15TopKeyNBAPct VARCHAR,
            setSpotBreakRightNBAMade VARCHAR,
            setSpotBreakRightNBAAttempted VARCHAR,
            setSpotBreakRightNBAPct VARCHAR,
            setSpotCornerRightNBAMade VARCHAR,
            setSpotCornerRightNBAAttempted VARCHAR,
            setSpotCornerRightNBAPct VARCHAR,
            setOffDrib15BreakLeft VARCHAR,
            setSpotOffDrib15TopKey VARCHAR,
            setOffDrib15BreakRight VARCHAR,
            setOnMove15 VARCHAR,
            setOnMoveCollege VARCHAR,
            setOffDrib15BreakLeftMade VARCHAR,
            setOffDrib15BreakLeftAttempted VARCHAR,
            setOffDrib15BreakLeftPct VARCHAR,
            setSpotOffDrib15TopKeyMade VARCHAR,
            setSpotOffDrib15TopKeyAttempted VARCHAR,
            setSpotOffDrib15TopKeyPct VARCHAR,
            setOffDrib15BreakRightMade VARCHAR,
            setOffDrib15BreakRightAttempted VARCHAR,
            setOffDrib15BreakRightPct VARCHAR,
            setOnMove15Made VARCHAR,
            setOnMove15Attempted VARCHAR,
            setOnMove15Pct VARCHAR,
            setOnMoveCollegeMade VARCHAR,
            setOnMoveCollegeAttempted VARCHAR,
            setOnMoveCollegePct VARCHAR,
            setOffDribBreakLeftCollege VARCHAR,
            setOffDribTopKeyCollege VARCHAR,
            setOffDribBreakRightCollege VARCHAR,
            setOffDribBreakLeftCollegeMade VARCHAR,
            setOffDribBreakLeftCollegeAttempted VARCHAR,
            setOffDribBreakLeftCollegePct VARCHAR,
            setOffDribTopKeyCollegeMade VARCHAR,
            setOffDribTopKeyCollegeAttempted VARCHAR,
            setOffDribTopKeyCollegePct VARCHAR,
            setOffDribBreakRightCollegeMade VARCHAR,
            setOffDribBreakRightCollegeAttempted VARCHAR,
            setOffDribBreakRightCollegePct VARCHAR
        )
`

const createDraftQuery = `
CREATE TABLE draft(
    yearDraft INTEGER,
    numberPickOverall VARCHAR,
    numberRound VARCHAR,
    numberRoundPick VARCHAR,
    namePlayer VARCHAR,
    slugTeam VARCHAR,
    nameOrganizationFrom VARCHAR,
    typeOrganizationFrom VARCHAR,
    idPlayer VARCHAR,
    idTeam INTEGER,
    nameTeam VARCHAR,
    cityTeam VARCHAR,
    teamName VARCHAR,
    PLAYER_PROFILE_FLAG VARCHAR,
    slugOrganizationTypeFrom VARCHAR,
    locationOrganizationFrom VARCHAR
)
`;

const createPlayerQuery = `
    CREATE TABLE player(
        id INTEGER,
        full_name VARCHAR,
        first_name VARCHAR,
        last_name VARCHAR,
        is_active VARCHAR
    )
`
const createPlayerBiosQuery = `
CREATE TABLE player_bios(
    namePlayerBREF VARCHAR,
    urlPlayerBioBREF VARCHAR,
    nameTable VARCHAR,
    urlPlayerImageBREF VARCHAR,
    slugPlayerBREF VARCHAR,
    numberTransactionPlayer VARCHAR,
    dateTransaction VARCHAR,
    descriptionTransaction VARCHAR,
    isGLeagueMovement VARCHAR,
    isDraft VARCHAR,
    isSigned VARCHAR,
    isWaived VARCHAR,
    isTraded VARCHAR,
    slugSeason VARCHAR,
    nameTeam VARCHAR,
    slugLeague VARCHAR,
    amountSalary VARCHAR,
    detailsContract VARCHAR,
    namePronunciation VARCHAR,
    namePosition VARCHAR,
    heightInches VARCHAR,
    weightLBS VARCHAR,
    dateBirth VARCHAR,
    locationBirthplace VARCHAR,
    cityBirthplace VARCHAR,
    stateBirthplace VARCHAR,
    nameCollege VARCHAR,
    nameHighSchool VARCHAR,
    dateNBADebut VARCHAR,
    careerLength VARCHAR,
    yearsExperience VARCHAR,
    nameTwitter VARCHAR,
    yearHighSchool VARCHAR,
    rankHighSchool VARCHAR,
    dateDeath VARCHAR,
    highSchools VARCHAR,
    descriptionRelatives VARCHAR,
    descriptionHOF VARCHAR,
    playerNicknames VARCHAR,
    colleges VARCHAR
);
`;

const createGameInactivePlayersQuery = `
CREATE TABLE game_inactive_players (
    PLAYER_ID INTEGER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    JERSEY_NUM VARCHAR,
    TEAM_ID VARCHAR,
    TEAM_CITY VARCHAR,
    TEAM_NAME VARCHAR,
    TEAM_ABBREVIATION VARCHAR,
    GAME_ID VARCHAR
)
`;
const createGameQuery = `
    CREATE TABLE game(
        GAME_ID INTEGER,
        SEASON_ID INTEGER,
        TEAM_ID_HOME INTEGER,
        TEAM_ABBREVIATION_HOME VARCHAR,
        TEAM_NAME_HOME VARCHAR,
        GAME_DATE VARCHAR,
        MATCHUP_HOME VARCHAR,
        WL_HOME VARCHAR,
        MIN_HOME VARCHAR,
        FGM_HOME VARCHAR,
        FGA_HOME VARCHAR,
        FG_PCT_HOME VARCHAR,
        FG3M_HOME VARCHAR,
        FG3A_HOME VARCHAR,
        FG3_PCT_HOME VARCHAR,
        FTM_HOME VARCHAR,
        FTA_HOME VARCHAR,
        FT_PCT_HOME VARCHAR,
        OREB_HOME VARCHAR,
        DREB_HOME VARCHAR,
        REB_HOME VARCHAR,
        AST_HOME VARCHAR,
        STL_HOME VARCHAR,
        BLK_HOME VARCHAR,
        TOV_HOME VARCHAR,
        PF_HOME VARCHAR,
        PTS_HOME INTEGER,
        PLUS_MINUS_HOME VARCHAR,
        VIDEO_AVAILABLE_HOME VARCHAR,
        TEAM_ID_AWAY VARCHAR,
        TEAM_ABBREVIATION_AWAY VARCHAR,
        TEAM_NAME_AWAY VARCHAR,
        MATCHUP_AWAY VARCHAR,
        WL_AWAY VARCHAR,
        MIN_AWAY VARCHAR,
        FGM_AWAY VARCHAR,
        FGA_AWAY VARCHAR,
        FG_PCT_AWAY VARCHAR,
        FG3M_AWAY VARCHAR,
        FG3A_AWAY VARCHAR,
        FG3_PCT_AWAY VARCHAR,
        FTM_AWAY VARCHAR,
        FTA_AWAY VARCHAR,
        FT_PCT_AWAY VARCHAR,
        OREB_AWAY VARCHAR,
        DREB_AWAY VARCHAR,
        REB_AWAY VARCHAR,
        AST_AWAY VARCHAR,
        STL_AWAY VARCHAR,
        BLK_AWAY VARCHAR,
        TOV_AWAY VARCHAR,
        PF_AWAY VARCHAR,
        PTS_AWAY INTEGER,
        PLUS_MINUS_AWAY VARCHAR,
        VIDEO_AVAILABLE_AWAY VARCHAR,
        GAME_DATE_EST VARCHAR,
        GAME_SEQUENCE VARCHAR,
        GAME_STATUS_ID VARCHAR,
        GAME_STATUS_TEXT VARCHAR,
        GAMECODE VARCHAR,
        HOME_TEAM_ID VARCHAR,
        VISITOR_TEAM_ID VARCHAR,
        SEASON VARCHAR,
        LIVE_PERIOD VARCHAR,
        LIVE_PC_TIME VARCHAR,
        NATL_TV_BROADCASTER_ABBREVIATION VARCHAR,
        LIVE_PERIOD_TIME_BCAST VARCHAR,
        WH_STATUS VARCHAR,
        TEAM_CITY_HOME VARCHAR,
        PTS_PAINT_HOME VARCHAR,
        PTS_2ND_CHANCE_HOME VARCHAR,
        PTS_FB_HOME VARCHAR,
        LARGEST_LEAD_HOME VARCHAR,
        LEAD_CHANGES_HOME VARCHAR,
        TIMES_TIED_HOME VARCHAR,
        TEAM_TURNOVERS_HOME VARCHAR,
        TOTAL_TURNOVERS_HOME VARCHAR,
        TEAM_REBOUNDS_HOME VARCHAR,
        PTS_OFF_TO_HOME VARCHAR,
        TEAM_CITY_AWAY VARCHAR,
        PTS_PAINT_AWAY VARCHAR,
        PTS_2ND_CHANCE_AWAY VARCHAR,
        PTS_FB_AWAY VARCHAR,
        LARGEST_LEAD_AWAY VARCHAR,
        LEAD_CHANGES_AWAY VARCHAR,
        TIMES_TIED_AWAY VARCHAR,
        TEAM_TURNOVERS_AWAY VARCHAR,
        TOTAL_TURNOVERS_AWAY VARCHAR,
        TEAM_REBOUNDS_AWAY VARCHAR,
        PTS_OFF_TO_AWAY VARCHAR,
        LEAGUE_ID VARCHAR,
        GAME_DATE_DAY VARCHAR,
        ATTENDANCE VARCHAR,
        GAME_TIME VARCHAR,
        TEAM_CITY_NAME_HOME VARCHAR,
        TEAM_NICKNAME_HOME VARCHAR,
        TEAM_WINS_LOSSES_HOME VARCHAR,
        PTS_QTR1_HOME VARCHAR,
        PTS_QTR2_HOME VARCHAR,
        PTS_QTR3_HOME VARCHAR,
        PTS_QTR4_HOME VARCHAR,
        PTS_OT1_HOME VARCHAR,
        PTS_OT2_HOME VARCHAR,
        PTS_OT3_HOME VARCHAR,
        PTS_OT4_HOME VARCHAR,
        PTS_OT5_HOME VARCHAR,
        PTS_OT6_HOME VARCHAR,
        PTS_OT7_HOME VARCHAR,
        PTS_OT8_HOME VARCHAR,
        PTS_OT9_HOME VARCHAR,
        PTS_OT10_HOME VARCHAR,
        PTS_HOME_y VARCHAR,
        TEAM_CITY_NAME_AWAY VARCHAR,
        TEAM_NICKNAME_AWAY VARCHAR,
        TEAM_WINS_LOSSES_AWAY VARCHAR,
        PTS_QTR1_AWAY VARCHAR,
        PTS_QTR2_AWAY VARCHAR,
        PTS_QTR3_AWAY VARCHAR,
        PTS_QTR4_AWAY VARCHAR,
        PTS_OT1_AWAY VARCHAR,
        PTS_OT2_AWAY VARCHAR,
        PTS_OT3_AWAY VARCHAR,
        PTS_OT4_AWAY VARCHAR,
        PTS_OT5_AWAY VARCHAR,
        PTS_OT6_AWAY VARCHAR,
        PTS_OT7_AWAY VARCHAR,
        PTS_OT8_AWAY VARCHAR,
        PTS_OT9_AWAY VARCHAR,
        PTS_OT10_AWAY VARCHAR,
        LAST_GAME_ID VARCHAR,
        LAST_GAME_DATE_EST VARCHAR,
        LAST_GAME_HOME_TEAM_ID VARCHAR,
        LAST_GAME_HOME_TEAM_CITY VARCHAR,
        LAST_GAME_HOME_TEAM_NAME VARCHAR,
        LAST_GAME_HOME_TEAM_ABBREVIATION VARCHAR,
        LAST_GAME_HOME_TEAM_POINTS VARCHAR,
        LAST_GAME_VISITOR_TEAM_ID VARCHAR,
        LAST_GAME_VISITOR_TEAM_CITY VARCHAR,
        LAST_GAME_VISITOR_TEAM_NAME VARCHAR,
        LAST_GAME_VISITOR_TEAM_CITY1 VARCHAR,
        LAST_GAME_VISITOR_TEAM_POINTS VARCHAR,
        HOME_TEAM_WINS VARCHAR,
        HOME_TEAM_LOSSES VARCHAR,
        SERIES_LEADER VARCHAR,
        VIDEO_AVAILABLE_FLAG VARCHAR,
        PT_AVAILABLE VARCHAR,
        PT_XYZ_AVAILABLE VARCHAR,
        HUSTLE_STATUS VARCHAR,
        HISTORICAL_STATUS VARCHAR
    )
`;

const createGameOficialsQuery = `
        CREATE TABLE game_officials(
            OFFICIAL_ID VARCHAR,
            FIRST_NAME VARCHAR,
            LAST_NAME VARCHAR,
            JERSEY_NUM VARCHAR,
            GAME_ID VARCHAR
        );
`;

const createNewsMissingQuery = `
        CREATE TABLE news_missing(
            link VARCHAR,
            exception VARCHAR,
            extraction_date VARCHAR
        );
`;

const createNewsQuery = `
        CREATE TABLE news(
            title VARCHAR,
            author VARCHAR,
            published_date VARCHAR,
            published_date_precision VARCHAR,
            link VARCHAR,
            clean_url VARCHAR,
            summary VARCHAR,
            rights VARCHAR,
            rank VARCHAR,
            topic VARCHAR,
            country VARCHAR,
            language VARCHAR,
            authors VARCHAR,
            media VARCHAR,
            is_opinion VARCHAR,
            twitter_account VARCHAR,
            _score VARCHAR,
            _id VARCHAR,
            page_number VARCHAR,
            query VARCHAR,
            text VARCHAR,
            top_image VARCHAR,
            images VARCHAR,
            movies VARCHAR,
            html VARCHAR,
            article_html VARCHAR,
            querystring_q VARCHAR,
            querystring_lang VARCHAR,
            querystring_page_size VARCHAR,
            querystring_from VARCHAR,
            querystring_to VARCHAR,
            querystring_page VARCHAR,
            scrape_date VARCHAR
        );
`;

const createPlayerAttributesQuery = `
            CREATE TABLE player_attributes(
                ID VARCHAR,
                FIRST_NAME VARCHAR,
                LAST_NAME VARCHAR,
                DISPLAY_FIRST_LAST VARCHAR,
                DISPLAY_LAST_COMMA_FIRST VARCHAR,
                DISPLAY_FI_LAST VARCHAR,
                PLAYER_SLUG VARCHAR,
                BIRTHDATE VARCHAR,
                SCHOOL VARCHAR,
                COUNTRY VARCHAR,
                LAST_AFFILIATION VARCHAR,
                HEIGHT FLOAT,
                WEIGHT FLOAT,
                SEASON_EXP VARCHAR,
                JERSEY VARCHAR,
                POSITION VARCHAR,
                ROSTERSTATUS VARCHAR,
                GAMES_PLAYED_CURRENT_SEASON_FLAG VARCHAR,
                TEAM_ID VARCHAR,
                TEAM_NAME VARCHAR,
                TEAM_ABBREVIATION VARCHAR,
                TEAM_CODE VARCHAR,
                TEAM_CITY VARCHAR,
                PLAYERCODE VARCHAR,
                FROM_YEAR VARCHAR,
                TO_YEAR VARCHAR,
                DLEAGUE_FLAG VARCHAR,
                NBA_FLAG VARCHAR,
                GAMES_PLAYED_FLAG VARCHAR,
                DRAFT_YEAR VARCHAR,
                DRAFT_ROUND VARCHAR,
                DRAFT_NUMBER VARCHAR,
                PTS VARCHAR,
                AST VARCHAR,
                REB VARCHAR,
                ALL_STAR_APPEARANCES VARCHAR,
                PIE VARCHAR
            );
`;

const createPlayerSalaryQuery = `
            CREATE TABLE player_salary (
                slugSeason VARCHAR,
                nameTeam VARCHAR,
                namePlayer VARCHAR,
                statusPlayer VARCHAR,
                isFinalSeason VARCHAR,
                isWaived VARCHAR,
                isOnRoster VARCHAR,
                isNonGuaranteed VARCHAR,
                isTeamOption VARCHAR,
                isPlayerOption VARCHAR,
                typeContractDetail VARCHAR,
                value VARCHAR
            )
`;

const createTeamAttributesQuery = `
            CREATE TABLE team_attributes (
                ID VARCHAR,
                ABBREVIATION VARCHAR,
                NICKNAME VARCHAR,
                YEARFOUNDED VARCHAR,
                CITY VARCHAR,
                ARENA VARCHAR,
                ARENACAPACITY VARCHAR,
                OWNER VARCHAR,
                GENERALMANAGER VARCHAR,
                HEADCOACH VARCHAR,
                DLEAGUEAFFILIATION VARCHAR,
                FACEBOOK_WEBSITE_LINK VARCHAR,
                INSTAGRAM_WEBSITE_LINK VARCHAR,
                TWITTER_WEBSITE_LINK VARCHAR
            );
`;
const createTeamHistoryQuery = `
            CREATE TABLE team_history(
                ID VARCHAR,
                CITY VARCHAR,
                NICKNAME VARCHAR,
                YEARFOUNDED VARCHAR,
                YEARACTIVETILL VARCHAR
            );
`;

const createTeamSalaryQuery = `
            CREATE TABLE team_salary(
                nameTeam VARCHAR,
                slugTeam VARCHAR,
                urlTeamSalaryHoopsHype VARCHAR,
                X2020_21 VARCHAR,
                X2021_22 VARCHAR,
                X2022_23 VARCHAR,
                X2023_24 VARCHAR,
                X2024_25 VARCHAR,
                X2025_26 VARCHAR
            );
`;

const createTeamQuery = `
            CREATE TABLE team(
                id VARCHAR,
                full_name VARCHAR,
                abbreviation VARCHAR,
                nickname VARCHAR,
                city VARCHAR,
                state VARCHAR,
                year_founded VARCHAR
            )
`;

module.exports = {
    createDraftCombineQuery,
    createDraftQuery,
    createPlayerBiosQuery,
    createGameQuery,
    createGameInactivePlayersQuery,
    createPlayerQuery,
    createGameOficialsQuery,
    createNewsMissingQuery,
    createNewsQuery,
    createPlayerAttributesQuery,
    createPlayerSalaryQuery,
    createTeamAttributesQuery,
    createTeamHistoryQuery,
    createTeamSalaryQuery,
    createTeamQuery
};